### ISSUE TITLE
Tracking Issue: Nuxt 3 Upgrade

### ISSUE THREAD

**Issue by Teages** [Cytoid/cytoid.io#117]
## Check important dependencies
- [x] That's all.
- [ ] Apollo
- [ ] axios

## Check ans remove unsupport dependencies
- [x] That's all.

- [ ] `@nuxtjs/pwa`: not work in nuxt 3
- [ ] `buefy`: not support vue 3 -> use `Oruga`
- [ ] `vee-validate`: upgrade to 4.x
- [ ] `vue-easymde`: only support vue 2 -> use [vue-markdown-editor](https://github.com/code-farmer-i/vue-markdown-editor)
- [ ] `vue-parallax-js`: ???
- [ ] `vue-tweet-embed`: not work in nuxt 3

## Check unsupport feature

- [ ] That's all
- [ ] jsx support: it seems it has lots of problem

## Tests

- [ ] `Home`

Levels
- [ ] `Levels`
- [ ] `Levels/[id]`
- [ ] `Levles/[id]/manage`

Collections
- [ ] `Collections`
- [ ] `Collections/[id]`
- [ ] `Collections/[id]/manage`

Posts
- [ ] `Posts`
- [ ] `Posts/[id]`
- [ ] `Posts/[id]/manage`

Pages
- [ ] `Pages/[id]`

Profile
- [ ] `Profile/[id]`

Session
- [ ] `Session/link`
- [ ] `Session/login`
- [ ] `Session/signup`
- [ ] `Session/reset/[token]`
- [ ] `Session/reset`

Settings
- [ ] `Settings/account`
- [ ] `Settings/donation`
- [ ] `Settings/profile`
- [ ] `Settings/security`

Studio
- [ ] `Studio/analytics`
- [ ] `Studio/collections`
- [ ] `Studio/levels`
- [ ] `Studio/posts`
- [ ] `Studio/sudo`
- [ ] `Studio/users`

Others
- [ ] `credits`
- [ ] `library`
- [ ] `session`
- [ ] `settings`
- [ ] `studio`

**Comment by Teages** [comment]
drop, will rebuild the whole io
